# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c05263fb69e4d2783d8f44b4a10753fd8b3d8852b92e3fbc3ce7164b874c732fa9a9e51535f9cda0b12d5fdecfcaa14a776118b146fe7bf1115d68efb6972d7a

test:
  secret_key_base: 3521546efe1b2f8741c9db83ade1deb3c293d9349ae272a46e010fe9e6eaafdd0d6708590189dc009d059f3d5fd31827c79d5ff786e6dcba5ffaba0153cacb38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
